ThemeDescription="You still there?"
ThemeAuthor="keico-o"
Look="flat"

TitleButtonsLeft="s"
TitleButtonsRight="xmi"
TitleButtonsSupported="xmis"
TitleBarHeight=17
TitleBarJoinRight=1

BorderSizeX=4
BorderSizeY=4
CornerSizeX=24
CornerSizeY=24
DlgBorderSizeX=3
DlgBorderSizeY=3

ColorNormalButton="#D9CFD0"
ColorNormalButtonText="#4D0F50"
ColorActiveButton="#D9CFD0"
ColorActiveButtonText="#4D0F50"
ColorNormalTitleBarText="#966A8E"
ColorActiveTitleBarText="#4D0F50"

ColorNormalMenu="#D9CFD0"
ColorActiveMenuItem="#FE92A1"
ColorNormalMenuItemText="#4D0F50"
ColorActiveMenuItemText="#4D0F50"
ColorDisabledMenuItemText="#966A8E"

ColorMoveSizeStatus="#000000"
ColorMoveSizeStatusText="#FFFFFF"

TitleFontNameXft	         = 	  "Tahoma8pt:size=8:bold"
MenuFontNameXft	         =    "Tahoma8pt:size=8"
MinimizedWindowFontNameXft =    "Tahoma8pt:size=8"
ActiveButtonFontNameXft    =    "Tahoma8pt:size=8"
NormalButtonFontNameXft    =    "Tahoma8pt:size=8"
QuickSwitchFontNameXft     =    "Tahoma8pt:size=8"
ListBoxFontNameXft         =    "Tahoma8pt:size=8"
StatusFontNameXft          =    "Tahoma8pt:size=8"
ToolTipFontNameXft         =    "Tahoma8pt:size=8"
ActiveTaskBarFontNameXft   =    "Tahoma8pt:size=8:bold"
NormalTaskBarFontNameXft   =    "Tahoma8pt:size=8"
ClockFontNameXft           =    "Tahoma8pt:size=8"
ApmFontNameXft             =    "Tahoma8pt:size=8"
LabelFontNameXft           =    "Tahoma8pt:size=8"

ShowMenuButtonIcon=1
