ThemeDescription="You still there?"
ThemeAuthor=keico-o
Look="retro"

TitleButtonsLeft="s"
TitleButtonsRight="xmi"
TitleButtonsSupported="xmis"
TitleBarCentered=1
TitleBarHeight=17
BorderSizeX=4
BorderSizeY=4
CornerSizeX=24
CornerSizeY=24
DlgBorderSizeX=4
DlgBorderSizeY=4

ColorNormalButton="#D9CFD0"
ColorNormalButtonText="#4D0F50"
ColorActiveButton="#D9CFD0"
ColorActiveButtonText="#4D0F50"
ColorNormalTitleBarText="#966A8E"
ColorActiveTitleBarText="#4D0F50"

ColorNormalMenu="#D9CFD0"
ColorActiveMenuItem="#FE92A1"
ColorNormalMenuItemText="#4D0F50"
ColorActiveMenuItemText="#4D0F50"
ColorDisabledMenuItemText="#966A8E"

ColorMoveSizeStatus="#000000"
ColorMoveSizeStatusText="#FFFFFF"

ActiveButtonFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
NormalButtonFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
ClockFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
QuickSwitchFontName="-b&h-lucida-medium-r-*-*-10-*-*-*-*-*-*-*"
ListBoxFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
MenuFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
StatusFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
TitleFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"
ToolTipFontName="-b&h-lucida-medium-r-*-*-11-*-*-*-*-*-*-*"

ShowMenuButtonIcon=0
